Implemented family kit task cleanup
OpenSRP/opensrp-client-chw-core pull request #336
Opened 2020-11-18 06:49 UTC by qaziabubakar-vd

Implemented family kit task cleanup
Incremented library version to 1.5.26-SNAPSHOT

Linked issue https://github.com/OpenSRP/opensrp-client-chw/issues/1546

2020-11-18 13:26 UTC, rkodev requested changes

2020-11-18 13:26 UTC, rkodev commented on opensrp-chw-core/src/main/java/org/smartregister/chw/core/repository/ScheduleRepository.java
> +    public void deleteChildMember(String baseEntityID) {
Use a soft delete in when deleting from ec_child table

2020-11-18 13:26 UTC, rkodev commented on opensrp-chw-core/src/main/java/org/smartregister/chw/core/repository/ScheduleRepository.java
> +    public void deleteChildMember(String baseEntityID) {
i.e is_closed field

2020-11-20 12:00 UTC, zzainulabidin approved these changes

2020-11-20 12:54 UTC, merged