Changed client-core version to 4.2.13
OpenSRP/opensrp-client-chw-core pull request #411
Opened 2021-03-22 11:28 UTC by qaziabubakar-vd

Linked Issue https://github.com/OpenSRP/opensrp-client-chw/issues/1743

2021-03-22 12:29 UTC, rkodev requested changes

2021-03-22 12:29 UTC, rkodev commented on opensrp-chw-core/src/main/java/org/smartregister/chw/core/utils/ReportUtils.java
>          JSONObject stepOne = form.getJSONObject(org.smartregister.chw.anc.util.JsonFormUtils.STEP1);
This would result on an NPE, we should execute all the code referencing the form within the try catch

2021-03-22 12:29 UTC, rkodev commented on opensrp-chw-core/src/main/java/org/smartregister/chw/core/interactor/CoreCommunityRespondersInteractor.java
>          Event baseEvent = org.smartregister.chw.anc.util.JsonFormUtils.processJsonForm(allSharedPreferences, form.toString(), CoreConstants.TABLE_NAME.COMMUNITY_RESPONDERS);
This would result on an NPE, we should execute all the code referencing the form within the try catch

2021-03-22 12:29 UTC, rkodev commented on opensrp-chw-core/src/main/java/org/smartregister/chw/core/activity/CoreCommunityRespondersRegisterActivity.java
>                  startFormActivity(form);
This would result on an NPE, we should execute all the code referencing the form within the try catch

2021-04-01 07:17 UTC, rkodev commented
@qaziabubakar We updated the version of core to a newer version that this one already, this will be a regression

2021-04-01 07:19 UTC, qaziabubakar-vd commented
Already on the updated the version of core.

2021-04-01 07:19 UTC, closed without merging